version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - modernize
    - nilnil
    - nolintlint
    - prealloc
    - revive
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style

    errorlint:
      errorf: true
      asserts: true
      comparison: true

    errcheck:
      check-blank: true

    misspell:
      locale: US

    nolintlint:
      require-explanation: true
      require-specific: true

    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true

    testifylint:
      enable-all: true

  exclusions:
    generated: strict
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - goconst
          - gosec
          - unparam
      - path: _test\.go
        linters:
          - modernize

run:
  timeout: 5m
